name: AI Auto Dev

on:
  issues:
    types: [opened, edited, labeled]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  build:
    if: |
      github.event_name == 'workflow_dispatch' ||
      contains(github.event.issue.labels.*.name, 'ai-dev')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Aider
        run: |
          python3 -m pip install --upgrade pip
          pip install 'aider-chat[anthropic,openai]'

      - name: Prepare prompt
        run: |
          mkdir -p .aider
          # heredocにしてシェル展開エスケープ
          cat > .aider/issue.txt <<'EOF'
          ${{ github.event.issue.title }}

          ${{ github.event.issue.body }}
          EOF

      - name: Choose model & flags
        id: model
        run: |
          if [ -n "${{ secrets.ANTHROPIC_API_KEY }}" ]; then
            echo "model=anthropic/claude-3.5-sonnet" >> $GITHUB_OUTPUT
          else
            echo "model=openai/gpt-4.1" >> $GITHUB_OUTPUT
          fi

      - name: Run AI change (Aider)
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          set -e
          git config user.name  "ai-bot"
          git config user.email "ai-bot@users.noreply.github.com"
          BR="ai/issue-${{ github.event.issue.number || github.run_id }}"
          git checkout -b "$BR"

          # ここでは . (リポジトリルート) だけ渡して、
          # 無視したいものは .aiderignore に書く
          echo ".git/" > .aiderignore
          echo ".github/" >> .aiderignore
          echo "node_modules/" >> .aiderignore
          echo ".next/" >> .aiderignore
          echo "supabase/" >> .aiderignore
          echo "sql/" >> .aiderignore

          aider \
            --model "${{ steps.model.outputs.model }}" \
            --commit \
            --yes \
            --message-file .aider/issue.txt \
            --edit-format diff \
            .

          git push -u origin "$BR"

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          title: "feat(ai): implement #${{ github.event.issue.number }}"
          body: |
            Auto-generated by AI Auto Dev.
            Source issue: #${{ github.event.issue.number }}
          base: main
          head: ai/issue-${{ github.event.issue.number || github.run_id }}