name: AI Auto Dev

on:
  issues:
    types: [opened, edited, labeled]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  build:
    # 手動起動 or ai-dev ラベルの issue だけ実行
    if: |
      github.event_name == 'workflow_dispatch' ||
      contains(github.event.issue.labels.*.name, 'ai-dev')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Aider
        run: |
          python3 -m pip install --upgrade pip
          pip install 'aider-chat[anthropic,openai]'

      - name: Prepare prompt
        run: |
          mkdir -p .aider
          echo "${{ github.event.issue.title }}" > .aider/issue.txt || true
          echo "" >> .aider/issue.txt || true
          echo "${{ github.event.issue.body }}" >> .aider/issue.txt || true

      - name: Choose model & flags
        id: model
        run: |
          if [ -n "${{ secrets.ANTHROPIC_API_KEY }}" ]; then
            echo "model=anthropic/claude-3.5-sonnet" >> $GITHUB_OUTPUT
          else
            echo "model=openai/gpt-4.1" >> $GITHUB_OUTPUT
          fi

            - name: Run AI change (Aider)
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          set -e
          git config user.name  "ai-bot"
          git config user.email "ai-bot@users.noreply.github.com"
          BR="ai/issue-${{ github.event.issue.number || github.run_id }}"
          git checkout -b "$BR"

          aider \
            --model "${{ steps.model.outputs.model }}" \
            --commit \
            --yes \
            --message-file .aider/issue.txt \
            --include "app/**/*.ts" \
            --include "app/**/*.tsx" \
            --include "lib/**/*.ts" \
            --include "types/**/*.ts" \
            --include "public/**/*" \
            --edit-format diff

          git push -u origin "$BR"

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          title: "feat(ai): implement #${{ github.event.issue.number }}"
          body: |
            Auto-generated by AI Auto Dev.
            Source issue: #${{ github.event.issue.number }}
          base: main
          head: ai/issue-${{ github.event.issue.number || github.run_id }}
