      - name: Run AI change (Aider)
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          set -e

          git config user.name  "ai-bot"
          git config user.email "ai-bot@users.noreply.github.com"

          BR="ai/issue-${{ github.event.issue.number || github.run_id }}"
          git checkout -b "$BR"

          # 使うモデル（前ステップの出力）
          MODEL="${{ steps.model.outputs.model }}"

          # APIキーが存在するものだけフラグに追加
          FLAGS="--model \"$MODEL\" --commit --yes --message-file .aider/issue.txt --include app lib types public --no-include .github sql supabase node_modules .next --edit-format diff"
          if [ -n "$OPENAI_API_KEY" ]; then
            FLAGS="$FLAGS --openai-api-key \"$OPENAI_API_KEY\""
          fi
          if [ -n \"$ANTHROPIC_API_KEY\" ]; then
            FLAGS="$FLAGS --anthropic-api-key \"$ANTHROPIC_API_KEY\""
          fi

          # Aider 実行
          eval aider $FLAGS

          # 変更があったら push（なければスキップ）
          if ! git diff --quiet; then
            git add -A
            git commit -m "feat(ai): apply changes for issue #${{ github.event.issue.number || github.run_id }}"
          fi

          git push -u origin "$BR"