name: AI Auto Dev

on:
  issues:
    types: [opened, edited, labeled]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  build:
    if: |
      github.event_name == 'workflow_dispatch' ||
      contains(github.event.issue.labels.*.name, 'ai-dev')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Aider
        run: |
          python3 -m pip install --upgrade pip
          pip install 'aider-chat[anthropic,openai]'

      - name: Prepare prompt
        run: |
          mkdir -p .aider
          {
            echo "${{ github.event.issue.title }}"
            echo
            echo "${{ github.event.issue.body }}"
          } > .aider/issue.txt

      # ← ここで「両方キーがあるなら OpenAI を優先」に変更
      - name: Choose model
        id: model
        run: |
          if [ -n "${{ secrets.OPENAI_API_KEY }}" ]; then
            echo "model=openai/gpt-4o-mini" >> "$GITHUB_OUTPUT"
          elif [ -n "${{ secrets.ANTHROPIC_API_KEY }}" ]; then
            echo "model=anthropic/claude-3.5-sonnet" >> "$GITHUB_OUTPUT"
          else
            echo "No API key found" >&2
            exit 1
          fi

      - name: Run AI change (Aider)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          set -e

          git config user.name  "ai-bot"
          git config user.email "ai-bot@users.noreply.github.com"

          BR="ai/issue-${{ github.event.issue.number || github.run_id }}"
          # 既に同名ブランチがあっても失敗しないように
          git checkout -B "$BR"

          # リポジトリ「.」を明示し、編集対象は include で限定
          aider . \
            --model "${{ steps.model.outputs.model }}" \
            --message-file .aider/issue.txt \
            --commit \
            --yes \
            --edit-format diff \
            --include app \
            --include lib \
            --include types \
            --include public

          git push -u origin "$BR"

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          base: main
          head: ai/issue-${{ github.event.issue.number || github.run_id }}
          title: "feat(ai): implement #${{ github.event.issue.number }}"
          body: |
            Auto-generated by AI Auto Dev.
            Source issue: #${{ github.event.issue.number }}