name: AI Auto Dev

on:
  issues:
    types: [opened, edited, labeled]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  build:
    # 手動起動 or ai-dev ラベル付き Issue のときだけ動く
    if: |
      github.event_name == 'workflow_dispatch' ||
      contains(github.event.issue.labels.*.name, 'ai-dev')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (for local tooling if needed)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Aider
        run: |
          python3 -m pip install --upgrade pip
          pip install 'aider-chat[anthropic,openai]'

      - name: Prepare prompt
        run: |
          mkdir -p .aider
          printf "%s\n\n%s\n" "${{ github.event.issue.title || '' }}" "${{ github.event.issue.body || '' }}" > .aider/issue.txt

      - name: Choose model & provider
        id: model
        run: |
          if [ -n "${{ secrets.ANTHROPIC_API_KEY }}" ]; then
            echo "model=anthropic/claude-3.5-sonnet" >> "$GITHUB_OUTPUT"
            echo "provider=anthropic" >> "$GITHUB_OUTPUT"
          elif [ -n "${{ secrets.OPENAI_API_KEY }}" ]; then
            echo "model=openai/gpt-4.1" >> "$GITHUB_OUTPUT"
            echo "provider=openai" >> "$GITHUB_OUTPUT"
          else
            echo "Neither ANTHROPIC_API_KEY nor OPENAI_API_KEY is set" >&2
            exit 1
          fi

      - name: Run AI change (Aider)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          set -e

          # どちらか片方のキーだけを残す（aiderのプロバイダ誤認を避ける）
          if [ "${{ steps.model.outputs.provider }}" = "openai" ]; then
            export OPENAI_API_KEY="${OPENAI_API_KEY}"
            unset ANTHROPIC_API_KEY
          else
            export ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY}"
            unset OPENAI_API_KEY
          fi

          # Aider の作業フォルダをコミット対象外に
          if ! grep -qE '(^|/)\.aider/?$' .gitignore 2>/dev/null; then
            echo ".aider" >> .gitignore
          fi

          # 触らせたくない領域は .aiderignore で除外（aiderは--include未対応のため除外方式）
          cat > .aiderignore <<'EOF'
          .git/
          .github/
          node_modules/
          .next/
          supabase/
          sql/
          tests/
          test-results/
          # 静的ファイルは通常除外（必要ならこの行を削除）
          public/**/*
          EOF

          git config user.name  "ai-bot"
          git config user.email "ai-bot@users.noreply.github.com"

          BR="ai/issue-${{ github.event.issue.number || github.run_id }}"
          git checkout -b "$BR"

          # リポジトリのルート（.）を1つだけ渡すのがaiderの正解
          aider \
            --model "${{ steps.model.outputs.model }}" \
            --commit \
            --yes \
            --message-file .aider/issue.txt \
            --edit-format diff \
            .

          git push -u origin "$BR"

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          base: main
          head: ai/issue-${{ github.event.issue.number || github.run_id }}
          title: "feat(ai): implement #${{ github.event.issue.number }}"
          body: |
            Auto-generated by AI Auto Dev.
            Source issue: #${{ github.event.issue.number }}