name: Check Secrets Presence

on:
  workflow_dispatch:   # 手動で実行できるトリガー

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Show which secrets seem set
        run: |
          echo "OPENAI_API_KEY set?      ${{ secrets.OPENAI_API_KEY != '' }}"
          echo "ANTHROPIC_API_KEY set?   ${{ secrets.ANTHROPIC_API_KEY != '' }}"
          echo "SUPABASE_PROJECT_ID set? ${{ secrets.SUPABASE_PROJECT_ID != '' }}"
          echo "SERVICE_ROLE set?        ${{ secrets.SUPABASE_SERVICE_ROLE_KEY != '' }}"


